### ISSUE TITLE
Problem interpreting {.0%} or {.1f} or else numeric formats that worked well on previous 1.5.0.0 MS Charticulator. Especially on Axis Tick Formats.

### ISSUE THREAD

**Issue by SMusento23** [zBritva/charticulator-visual-community#22]
After downloading from https://appsource.microsoft.com, both Editor & VIEW custom visuals:

  charticulatorVisualCommunity_VIEW.1.0.14.0.pbiviz
  charticulatorVisualCommunity_EDITOR.1.0.14.0.pbiviz

... and activating both on a .pbix file, already working with previous Charticulator 1.5.0.0, 

Then when switching visual on a given Charticulator_1.5.0.0 chart to new "Charticulator Visual Community" (EDITOR or VIEW) fails to display chart.

Looks like there's a problem interpreting  {.0%} or {.1f} or else formats that work well on previous 1.5.0.0 MS Charticulator. Especially on axis Tick Formats.

Attached the is a .pbix with MS Charticulator's charts that cannot "convert" to use new Editor or View "Charticulator Visual Community". 
[PWBI_2.131.1203_Chartic.VisualComm_1.0.14.0_vs_Chartic_1.5.0.0_Tick Formats_Error.pbix.zip](https://github.com/user-attachments/files/16531858/PWBI_2.131.1203_Chartic.VisualComm_1.0.14.0_vs_Chartic_1.5.0.0_Tick.Formats_Error.pbix.zip)

**Comment by zBritva** [comment]
@SMusento23 thanks for reporting. I will check the issue.

**Comment by zBritva** [comment]
The new version with fix was approved for publication and should reach to end users in 2-3 weeks
