### ISSUE TITLE
Text Box Visibility Scale with "Greater Than 0" condition Not Showing Values If first data points are null. 

### ISSUE THREAD

**Issue by SMusento23** [zBritva/charticulator-visual-community#23]
Hi,
Issue noticed when using latest Editor v. 1.2.0.0 version in Power BI Desktop (July'2024 v. 2.131.1203). 

When switching a working chart with a "Greater Than 0" Visibility Scale on a TextBox, it fails to show values "Greater Than 0" if first data points are null. 

In fact, if those data points are filtered, then behaves as expected. 

If it is tried a negative value, e.g. "Greater than -1" ... it works.
If it is tried, e.g.  "Less than 20" ... it works. 

[PWBI_2.131.1203_Chartic.VisualComm_Editor_1.2.0.0_Issue with Greater Than Visibility.pbix.zip](https://github.com/user-attachments/files/16761020/PWBI_2.131.1203_Chartic.VisualComm_Editor_1.2.0.0_Issue.with.Greater.Than.Visibility.pbix.zip)
In attachment: .pbix file showing the issue

Thank You,
Regards 
Steve

PS: Thank You So Much, for the tough job you've undertaken to keep Charticulator alive.

**Comment by zBritva** [comment]
The workaround to fix it's the same as for https://github.com/zBritva/charticulator-visual-community/issues/27

I'm still investigating the issue.

**Comment by zBritva** [comment]
Fixed in ver 1.2.3
