### ISSUE TITLE
Charticulator V.C. 1.2.0.0 Editor's engine enters an infinite loop, when switching visual to it on a column + line Chart (multi plot)  

### ISSUE THREAD

**Issue by SMusento23** [zBritva/charticulator-visual-community#24]
Hi,

Unexpected animated behavior(infinite loop), when switching to Chartciculator V.C. 1.2.0.0, a given Column+Line cartesian Chart, implemented through 4 overlapped specialized Plots. Same chart was working fine in legacy Charticulator 1.5.0.0.

I'm sorry I cannot provide any hints, besides observing that the first plot, "Plot Bar Chart", look as having entered an infinite loop when trying to calculate x-axis positioning of Columns chart, moving back and forth horizontally.

Attached you can find a .pbix file showing the issue:
[PWBI_2.131.1203_Chartic.VC_Editor_1.2.0.0_Issue Unstable Switch from Chartic_1.5.0.0 to Chartic.VC_Editor_1.2.0.0.pbix.zip](https://github.com/user-attachments/files/16762185/PWBI_2.131.1203_Chartic.VC_Editor_1.2.0.0_Issue.Unstable.Switch.from.Chartic_1.5.0.0.to.Chartic.VC_Editor_1.2.0.0.pbix.zip)

Regards,
Esteban

**Comment by zBritva** [comment]
@SMusento23 Thanks for reporting.

Confirm issue.

As workaround to temroray fix:

* disable scrollbar for x axis, if you don't need it
![image](https://github.com/user-attachments/assets/0d3dfbe0-a27d-4f27-a175-b108ebf96d3e)

* or set windows size to 3:
![image](https://github.com/user-attachments/assets/b2be70de-8a98-478e-ba7c-edd89d49c01e)

**Comment by zBritva** [comment]
Fixed in View version
