### ISSUE TITLE
"Editor preview:" label behaviour of moving down charticulator's rendering, prevents from having a full WYSIWYG interface

### ISSUE THREAD

**Issue by SMusento23** [zBritva/charticulator-visual-community#25]
Hi,
It is a bit tricky to tune PBI's multiple visuals position and W x H 's size, in order to fit altogether in a single page.

Specially, if what's shown is shifted down by the Label "Editor preview:", and having to continuously switch back and forth between "_Editor" and "View" to see the "actual" rendering (no WYSIWYG in that case). 

Not to mention the case of multiple, single, integrated "tiny" KPIs designed through Charticulator, that doesn't even render if were shifted down, due to the "Editor preview:" label.

Is there a way of avoiding that label, besides having to switch to the "View" visual?

Otherwise, could it be implemented differently, may be as an overlapping label, and with a configurable font size?
 (i.e. "Editor" charticulator's rendering should start where the "View" version would start rendering it)

Regards,

Steve

**Comment by zBritva** [comment]
The version 1.3.0.0 has control to disable the preview label:

![image](https://github.com/user-attachments/assets/c2237301-35e8-4361-a664-425d0bd3848f)

**Comment by SMusento23** [comment]
Thank you so much. I've just downloaded it from appsource Microsoft's site.

Where is that control found in Power BI Desktop?
For instance, when selecting chart pointing Editor's version visual 1.3.0.0, the pwbi's "Format" sub-menu shows as in:

![image](https://github.com/user-attachments/assets/e4d05f36-e2b3-4e65-b988-819c2a27643a)
