### ISSUE TITLE
no effect of DataAxis attribute of "sum(WO_number)"

### ISSUE THREAD

**Issue by RickyWu313** [zBritva/charticulator-visual-community#29]
![image](https://github.com/user-attachments/assets/f7409ffc-9a01-489b-8b35-40601ec41662)

![image](https://github.com/user-attachments/assets/a6bb8e38-d6f5-47a9-a04a-40ff9a44e019)

I set  DataAxis attribute of "sum(WO_number)", but have no effect.

**Comment by RickyWu313** [comment]
[Uploading Chart_Nested_bar_Auto - copy.pbix.zip…]()

**Comment by zBritva** [comment]
@RickyWu313 make sure that each category has several values:

In this case aggregation functions works:
![image](https://github.com/user-attachments/assets/a707c313-7ebb-4504-ace7-a90cde1ec302)

In this case aggregation function doesn't make any sense:

![image](https://github.com/user-attachments/assets/eede6632-60bc-4ca9-9860-b6fcbf96c716)

values of each function (SUM, AVR, MAX, MIX e.t.c) are the same

**Comment by RickyWu313** [comment]
![image](https://github.com/user-attachments/assets/b7c09d19-cc16-4335-9e4e-2e9037c59818)
use “group by” to aggregation function SUM，
![image](https://github.com/user-attachments/assets/84feafbf-f74f-4957-aed1-f944293b0475)
but  DataAxis attribute of "sum(WO_number)" still is "average"
![image](https://github.com/user-attachments/assets/0688494c-9130-4d2e-9225-c81f1e51ed46)
[Uploading Chart_Nested_bar_Auto - copy.pbix.zip…]()

**Comment by RickyWu313** [comment]
![image](https://github.com/user-attachments/assets/a6d978d4-c5b9-49c2-b771-3fe83b1bcc0e)

**Comment by RickyWu313** [comment]
Hello, I have found cause of my issue about aggregation functions
![image](https://github.com/user-attachments/assets/537a9670-2a41-41fa-8a50-87ae9a87bb73)
![image](https://github.com/user-attachments/assets/4dd12cfd-c6e0-4d48-8109-ae0f0949a04b)
![image](https://github.com/user-attachments/assets/5169974a-c4c7-42e3-b873-07a229e8c836)
After using "Data Expression" , iusse is solved.
