### ISSUE TITLE
data label cannot be displayed

### ISSUE THREAD

**Issue by RickyWu313** [zBritva/charticulator-visual-community#31]
data labe of first bar cannot be displayed.
![image](https://github.com/user-attachments/assets/819671a1-5bcf-42ad-b406-f8093d6f286a)
[Uploading Chart_Nested_bar_Auto - copy.pbix.ZIP…]()

**Comment by RickyWu313** [comment]
[Chart_Nested_bar_Auto - copy.pbix.ZIP](https://github.com/user-attachments/files/17003011/Chart_Nested_bar_Auto.-.copy.pbix.ZIP)

**Comment by zBritva** [comment]
The issue was fixed in https://github.com/zBritva/charticulator/pull/42
