### ISSUE TITLE
Charticulator visual disapperad

### ISSUE THREAD

**Issue by Pavithranmckinsey** [zBritva/charticulator-visual-community#34]
Hello Team,

This is regards to charticulator power Bi Visual used in our report.

Visual has disappeared from our report and it is affecting our production. Consider as urgent request.

When we try to import the custom visual, getting error message.

Kindly help.

<img width="712" alt="Now" src="https://github.com/user-attachments/assets/cf4b82ac-7205-4a70-8a35-c325f694e7d8">
<img width="697" alt="Older" src="https://github.com/user-attachments/assets/d53671ec-db88-40fd-a615-d206fa7dcd44">

<img width="849" alt="Error_0" src="https://github.com/user-attachments/assets/60f79275-00c2-49de-a1b8-6753625d1473">
<img width="623" alt="Error_1" src="https://github.com/user-attachments/assets/bb37facf-cf1f-4c34-9f22-4fc12bdae0b9">

**Comment by Pavithranmckinsey** [comment]
followed the steps and its not working, still showing blank page
<img width="753" alt="image" src="https://github.com/user-attachments/assets/ccead86f-49a2-4543-86ab-26c246355197">

**Comment by Pavithranmckinsey** [comment]
Can we get the old charticulator back

**Comment by zBritva** [comment]
@Pavithranmckinsey you don't need it. The visual should be on the report, if you deleted it, you need to create from scratch.

**Comment by zBritva** [comment]
@Pavithranmckinsey Try to solution from discussion:
https://github.com/zBritva/charticulator-visual-community/discussions/28#discussioncomment-10639614
