### ISSUE TITLE
Charticulator visual sorting

### ISSUE THREAD

**Issue by Pavithranmckinsey** [zBritva/charticulator-visual-community#35]
Hello Team,

We've been developing a new visual with x axis(width) and y axis(height) as number values. However the bars are scatter.

Kindly help and consider as urgent as were struck.

<img width="551" alt="image" src="https://github.com/user-attachments/assets/e9aefb9f-0b37-4556-b77c-3f7113cdb34f">

Expectation;
<img width="697" alt="Older" src="https://github.com/user-attachments/assets/2868c734-0fb2-4b93-a56c-721c633d0b83">

Note - we're using the same variables and data is same 

Thanks,
Pavithran

**Comment by zBritva** [comment]
https://github.com/zBritva/charticulator-visual-community/issues/32

**Comment by zBritva** [comment]
As workaround use dev version of the editor on https://ilfat-galiev.im/ :
![image](https://github.com/user-attachments/assets/6aaf1d33-fb05-4807-b45b-b1718e19b745)
