### ISSUE TITLE
x axis and y-axis label are truncated

### ISSUE THREAD

**Issue by Pavithranmckinsey** [zBritva/charticulator-visual-community#36]
Hello Team,

x axis and y-axis label are truncated in the charticulator visual. Even though we change the data format, truncated values are not changing.

Kindly help

![image](https://github.com/user-attachments/assets/d9e3b17a-9a7b-4abc-874c-007ff910f00d)

**Comment by zBritva** [comment]
@Pavithranmckinsey clearefy, please.

I don't see what is wrong

**Comment by Pavithranmckinsey** [comment]
X axis label are truncated and has weird charecter 3e+2, 4e+2, 5e+2

**Comment by Pavithranmckinsey** [comment]
X axis label are truncated and has weird charecter 3e+2, 4e+2, 5e+2

**Comment by Pavithranmckinsey** [comment]
Any update ?

**Comment by zBritva** [comment]
Have you set the number format?

**Comment by Pavithranmckinsey** [comment]
Yes set the format but it is not working, how to change the decimal values in the visual ?
