### ISSUE TITLE
Charticulator visual is not working, and it is showing template error

### ISSUE THREAD

**Issue by jeevitha0368** [zBritva/charticulator-visual-community#37]
We have the charticulator visual used, and now microsoft removed the old one and added the new visual. when we download the report, it becomes blank , we should use only the charticulator community version(view) since it is microsoft certified and we cant use the editor one since our organization restricted to user uncertified microsoft visuals. We tried using the view one, but the template is not working maybe it is broken, we are not sure. Need help on this to resolve

**Comment by zBritva** [comment]
@jeevitha0368 review the discussion: https://github.com/zBritva/charticulator-visual-community/discussions/28#discussioncomment-10639614
