### ISSUE TITLE
Settings to "On" of Editor & View settings are not saved during Power BI .pbix file "SAVE".

### ISSUE THREAD

**Issue by SMusento23** [zBritva/charticulator-visual-community#39]
The setting to "ON" of both: <Hide editor preview> and <Hide default template> settings, are not saved when saving PWBI *.pbix file.
If you save the file and then reopen it on PWBI Desktop, both settings reappear on "Off" status.

Platform where happened: Win11, PWBI July'2024 and both Charticulator Editor versions 1.4.0.0 and 1.4.2.0

------------------------------------------------------------------------------------
              The version 1.3.0.0 has control to disable the preview label:

![image](https://github.com/user-attachments/assets/c2237301-35e8-4361-a664-425d0bd3848f)

_Originally posted by @zBritva in https://github.com/zBritva/charticulator-visual-community/issues/25#issuecomment-2405738166_

**Comment by zBritva** [comment]
On reopening PBI loads visuals from CDN, in CDN is 1.2.3 right now

**Comment by SMusento23** [comment]
> On reopening PBI loads visuals from CDN, in CDN is 1.2.3 right now

This is something I don't know, what do you mean that PBI loads visuals from CDN as 1.2.3?

The single *.pbix file was loaded with 1.4.0.0 and the updated to 1.4.2.0 Editor version(downloaded from official https://appsource.microsoft.com site). 
Those formatting attributes appeared afterwards, and what happens is that, when those settings are set to ON and you save&close the file, then, when you re-open it, they are found both reset to OFF.

**Comment by zBritva** [comment]
@SMusento23 check the visuals version after reopening file.

Loaded version of the visual works until closing the report (assuming that visuals from file is enabled for report)
